name: 'name'
description: 'description'
created_on: '1970-01-01'
mailing_list: 'mail'
meeting_url: 'url'
mature_level: 'startup'
mentors:
  - gitee_id: 'id'
    name: 'name'
    organization: 'organization'
    email: 'email'
  - gitee_id: 'id'
    name: 'name'
    organization: 'organization'
    email: 'email'
maintainers:
  - gitee_id: 'id'
    name: 'name'
    organization: 'organization'
    email: 'email'
  - gitee_id: 'id'
    name: 'name'
    organization: 'organization'
    email: 'email'
repositories:
  - repo:
    - 'org1/repo2'
    - 'org1/repo2'
  - admins:
    - gitee_id: 'id'
      name: 'name'
      organization: 'organization'
      email: 'email'
    - gitee_id: 'id'
      name: 'name'
      organization: 'organization'
      email: 'email'
  - committers:
      - gitee_id: 'id'
        name: 'name'
        organization: 'organization'
        email: 'email'
      - gitee_id: 'id'
        name: 'name'
        organization: 'organization'
        email: 'email'
  - contributor:
      - gitee_id: 'id'
        name: 'name'
        organization: 'organization'
        email: 'email'
      - gitee_id: 'id'
        name: 'name'
        organization: 'organization'
        email: 'email'